---
title: "epirice"
author: "Adam H Sparks"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{epirice}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{ggplot2}
  %\VignetteDepends{data.table}
---

## Predicting disease severity

```{r epirice}
library(epirice)
```

### Get weather data

```{r power}
 wth <- get_wth(
   lonlat = c(121.25562, 14.6774),
   dates = c("2000-05-15", "2000-12-31")
 )
```

### Predict bacterial blight

```{r predict_bb}
 bb <- predict_bacterial_blight(wth, emergence = "2000-05-18")
```

```{r bb}
summary(bb)
```
## Plotting using ggplot2

```{r ggplot2}
library(ggplot2)
library(tidyr)
```

### Sites

```{r plot_sites}
dat <- pivot_longer(
  bb,
  cols = c("diseased", "removed", "latent", "infectious"),
  names_to = "site",
  values_to = "value"
)

ggplot(data = dat,
       aes(
         x = dates,
         y = value,
         shape = site,
         linetype = site
       )) +
  labs(y = "Sites",
       x = "Date") +
  geom_line(aes(group = site, colour = site)) +
  geom_point(aes(colour = site))
```

### Severity

```{r plot_severity}
dat <- pivot_longer(
  bb,
  cols = "severity",
  names_to = "severity",
  values_to = "value"
)

ggplot(data = dat,
       aes(x = dates,
           y = value)) +
  labs(y = "Severity or Incidence",
       x = "Date") +
  geom_line() +
  geom_point()
```
