<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>epicrop • epicrop</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/journal/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="epicrop">
<meta property="og:description" content="epicrop">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">epicrop</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/epirice.html">epicrop</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/adamhsparks/epicrop/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="epirice_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>epicrop</h1>
                        <h4 class="author">Adam H Sparks</h4>
            
            <h4 class="date">2020-12-27</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/adamhsparks/epicrop/blob/master/vignettes/epirice.Rmd"><code>vignettes/epirice.Rmd</code></a></small>
      <div class="hidden name"><code>epirice.Rmd</code></div>

    </div>

    
    
<div id="introduction-to-epicrop" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction-to-epicrop" class="anchor"></a>Introduction to epicrop</h2>
<p><code>epicrop</code> provides an R package of the EPIRICE model as described in Savary <em>et al.</em> 2012. Default values derived from the literature suitable for modelling unmanaged disease severity of five rice diseases, bacterial blight; brown spot; leaf blast; sheath blight and tungro are provided. The model uses daily weather data to estimate disease severity. A function, <code><a href="../reference/get_wth.html">get_wth()</a></code> is provided to simplify downloading weather data from the <a href="https://power.larc.nasa.gov">NASA POWER web API</a> that are suitable for use in <code>epicrop</code>.</p>
<p>Using the package functions is designed to be straightforward for modelling rice disease risks, but flexible enough to accommodate other pathosystems using the <code><a href="../reference/SEIR.html">SEIR()</a></code> function. If you are interested in modelling other pathosystems, please refer to Savary <em>et al.</em> 2012 for the development of the parameters that were used for the rice diseases as derived from the existing literature and are implemented in the individual disease model functions.</p>
<div id="getting-started" class="section level3">
<h3 class="hasAnchor">
<a href="#getting-started" class="anchor"></a>Getting started</h3>
<p>Load the library.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/adamhsparks/epicrop/">epicrop</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="get-weather-data" class="section level3">
<h3 class="hasAnchor">
<a href="#get-weather-data" class="anchor"></a>Get weather data</h3>
<p>The most simple way to use the model is to download weather data from NASA POWER using <code><a href="../reference/get_wth.html">get_wth()</a></code>, which provides the data in a format suitable for use in the model and is freely available. See <code>?naspower::get_power()</code> for more details of this functionality and details on the data (Sparks 2018, Sparks 2020).</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Fetch weather for year 2000 season at the IRRI Zeigler Experiment Station</span>
<span class="va">wth</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/get_wth.html">get_wth</a></span><span class="op">(</span>
  lonlat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">121.25562</span>, <span class="fl">14.6774</span><span class="op">)</span>,
  dates <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"2000-01-01"</span>, <span class="st">"2000-12-31"</span><span class="op">)</span>
<span class="op">)</span>

<span class="va">wth</span></code></pre></div>
<pre><code>##        YYYYMMDD DOY  TEMP  TMIN  TMAX  TDEW  RHUM  RAIN      LAT      LON
##   1: 2000-01-01   1 24.25 22.68 27.40 22.67 90.84  9.80 14.67741 121.2556
##   2: 2000-01-02   2 24.10 22.39 27.34 22.44 90.38  5.01 14.67741 121.2556
##   3: 2000-01-03   3 23.56 21.91 26.71 21.49 88.12  1.67 14.67741 121.2556
##   4: 2000-01-04   4 23.41 21.57 26.93 21.27 87.72  0.74 14.67741 121.2556
##   5: 2000-01-05   5 23.83 21.21 27.98 21.68 87.73  0.35 14.67741 121.2556
##  ---                                                                     
## 362: 2000-12-27 362 24.27 22.65 26.20 23.06 92.93 26.32 14.67741 121.2556
## 363: 2000-12-28 363 24.39 23.16 26.87 23.08 92.33  6.67 14.67741 121.2556
## 364: 2000-12-29 364 24.39 22.58 27.46 22.94 91.57  7.19 14.67741 121.2556
## 365: 2000-12-30 365 24.96 22.60 28.50 22.67 87.13  2.97 14.67741 121.2556
## 366: 2000-12-31 366 24.22 21.26 28.49 21.95 87.21  3.04 14.67741 121.2556</code></pre>
</div>
<div id="predict-bacterial-blight" class="section level3">
<h3 class="hasAnchor">
<a href="#predict-bacterial-blight" class="anchor"></a>Predict bacterial blight</h3>
<p>All of the <code>predict_()</code> family of functions work in exactly the same manner. You provide them with weather data and an emergence date, that falls within the weather data provided, and they will return a data frame of disease severity over the season and other values associated with the model. See <code>?SEIR()</code> for more on the values returned.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Predict bacterial blight severity for the year 2000 wet season at IRRI</span>
<span class="va">bb_wet</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/predict_bacterial_blight.html">predict_bacterial_blight</a></span><span class="op">(</span><span class="va">wth</span>, emergence <span class="op">=</span> <span class="st">"2000-07-01"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bb_wet</span><span class="op">)</span></code></pre></div>
<pre><code>##      simday        dates                sites            latent        
##  Min.   :  0   Min.   :2000-06-30   Min.   : 100.0   Min.   :  0.0000  
##  1st Qu.: 30   1st Qu.:2000-07-30   1st Qu.: 947.2   1st Qu.:  0.6813  
##  Median : 60   Median :2000-08-29   Median :1809.4   Median : 10.4624  
##  Mean   : 60   Mean   :2000-08-29   Mean   :1627.4   Mean   : 51.7850  
##  3rd Qu.: 90   3rd Qu.:2000-09-28   3rd Qu.:2379.3   3rd Qu.: 87.7289  
##  Max.   :120   Max.   :2000-10-28   Max.   :2617.9   Max.   :217.5892  
##    infectious        removed          senesced         rateinf     
##  Min.   :  0.00   Min.   :  0.00   Min.   :   0.0   Min.   : 0.00  
##  1st Qu.:  1.00   1st Qu.:  0.00   1st Qu.: 115.6   1st Qu.: 0.00  
##  Median : 19.77   Median :  1.00   Median : 655.4   Median : 0.00  
##  Mean   :217.26   Mean   : 38.37   Mean   : 822.7   Mean   :10.82  
##  3rd Qu.:391.55   3rd Qu.: 21.46   3rd Qu.:1435.6   3rd Qu.:16.73  
##  Max.   :932.28   Max.   :413.01   Max.   :2369.0   Max.   :62.56  
##    rtransfer        rgrowth         rsenesced         diseased       
##  Min.   : 0.00   Min.   : 9.688   Min.   : 1.000   Min.   :   0.000  
##  1st Qu.: 0.00   1st Qu.:23.407   1st Qu.: 9.472   1st Qu.:   1.681  
##  Median : 0.00   Median :32.658   Median :22.135   Median :  31.627  
##  Mean   :10.13   Mean   :40.455   Mean   :20.026   Mean   : 307.417  
##  3rd Qu.:13.68   3rd Qu.:57.084   3rd Qu.:26.147   3rd Qu.: 629.709  
##  Max.   :62.56   Max.   :79.705   Max.   :59.794   Max.   :1292.132  
##     severity            lat             lon       
##  Min.   : 0.0000   Min.   :14.68   Min.   :121.3  
##  1st Qu.: 0.1772   1st Qu.:14.68   1st Qu.:121.3  
##  Median : 1.2067   Median :14.68   Median :121.3  
##  Mean   :10.2562   Mean   :14.68   Mean   :121.3  
##  3rd Qu.:21.5366   3rd Qu.:14.68   3rd Qu.:121.3  
##  Max.   :40.1701   Max.   :14.68   Max.   :121.3</code></pre>
</div>
</div>
<div id="plotting-using-ggplot2" class="section level2">
<h2 class="hasAnchor">
<a href="#plotting-using-ggplot2" class="anchor"></a>Plotting using ggplot2</h2>
<p>The data are in a wide format by default and need to be converted to long format for use in <code>ggplot2</code> if you wish to plot more than one variable at a time.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span></code></pre></div>
<div id="wet-season-sites" class="section level3">
<h3 class="hasAnchor">
<a href="#wet-season-sites" class="anchor"></a>Wet season sites</h3>
<p>The model records the number of sites for each bin daily, this can be graphed as follows.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>
  <span class="va">bb_wet</span>,
  cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"diseased"</span>, <span class="st">"removed"</span>, <span class="st">"latent"</span>, <span class="st">"infectious"</span><span class="op">)</span>,
  names_to <span class="op">=</span> <span class="st">"site"</span>,
  values_to <span class="op">=</span> <span class="st">"value"</span>
<span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">dat</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>
         x <span class="op">=</span> <span class="va">dates</span>,
         y <span class="op">=</span> <span class="va">value</span>,
         shape <span class="op">=</span> <span class="va">site</span>,
         linetype <span class="op">=</span> <span class="va">site</span>
       <span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Sites"</span>,
       x <span class="op">=</span> <span class="st">"Date"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>group <span class="op">=</span> <span class="va">site</span>, colour <span class="op">=</span> <span class="va">site</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="va">site</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Site states over time for bacterial blight"</span>,
       subtitle <span class="op">=</span> <span class="st">"Results for wet season year 2000 at IRRI Zeigler Experiment
       Station shown"</span>,
       caption <span class="op">=</span> <span class="st">"Weather data acknowledgement: These data were obtained from
       the NASA Langley Research Center POWER Project funded through the NASA
       Earth Science Directorate Applied Science Program."</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_light</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="epirice_files/figure-html/wet_plot_sites-1.png" width="672"></p>
</div>
<div id="wet-season-severity" class="section level3">
<h3 class="hasAnchor">
<a href="#wet-season-severity" class="anchor"></a>Wet season severity</h3>
<p>Plotting severity over time does not require any data manipulation.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">bb_wet</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dates</span>,
           y <span class="op">=</span> <span class="va">severity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Severity (%)"</span>,
       x <span class="op">=</span> <span class="st">"Date"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Bacterial blight disease progress over time"</span>,
       subtitle <span class="op">=</span> <span class="st">"Results for wet season year 2000 at IRRI Zeigler Experiment
       Station shown"</span>,
       caption <span class="op">=</span> <span class="st">"Weather data acknowledgement: These data were obtained from
       the NASA Langley Research Center POWER Project nfunded through the NASA
       Earth Science Directorate Applied Science Program."</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_light</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="epirice_files/figure-html/wet_plot_severity-1.png" width="672"></p>
</div>
</div>
<div id="comparing-epidemics" class="section level2">
<h2 class="hasAnchor">
<a href="#comparing-epidemics" class="anchor"></a>Comparing epidemics</h2>
<p>The most common way to compare disease epidemics in botanical epidemiology is to use the area under the disease progress curve (AUDPC) (Shaner and Finney 1977). This is easily calculated from the output of any of the <code>predict_*()</code> functions or a custom <code><a href="../reference/SEIR.html">SEIR()</a></code> run using the <em>epifitter</em> package (Alves and Del Ponte 2020).</p>
<p>Load <em>epifitter</em> and simulate the disease severity in the dry season starting in January to compare with the initial <code>bb_wet</code> results.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/AlvesKS/epifitter">epifitter</a></span><span class="op">)</span>

<span class="va">bb_dry</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/predict_bacterial_blight.html">predict_bacterial_blight</a></span><span class="op">(</span>wth <span class="op">=</span> <span class="va">wth</span>, emergence <span class="op">=</span> <span class="st">"2000-01-05"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bb_dry</span><span class="op">)</span></code></pre></div>
<pre><code>##      simday        dates                sites            latent      
##  Min.   :  0   Min.   :2000-01-04   Min.   : 100.0   Min.   : 0.000  
##  1st Qu.: 30   1st Qu.:2000-02-03   1st Qu.: 947.5   1st Qu.: 0.000  
##  Median : 60   Median :2000-03-04   Median :2525.4   Median : 1.223  
##  Mean   : 60   Mean   :2000-03-04   Mean   :1911.0   Mean   : 5.901  
##  3rd Qu.: 90   3rd Qu.:2000-04-03   3rd Qu.:2719.1   3rd Qu.: 7.487  
##  Max.   :120   Max.   :2000-05-03   Max.   :2778.3   Max.   :57.999  
##    infectious         removed          senesced         rateinf     
##  Min.   :  0.000   Min.   : 0.000   Min.   :   0.0   Min.   : 0.00  
##  1st Qu.:  1.000   1st Qu.: 0.000   1st Qu.: 115.6   1st Qu.: 0.00  
##  Median :  8.622   Median : 1.000   Median : 656.0   Median : 0.00  
##  Mean   : 30.882   Mean   : 9.681   Mean   : 840.8   Mean   : 1.18  
##  3rd Qu.: 54.999   3rd Qu.: 9.622   3rd Qu.:1476.9   3rd Qu.: 0.00  
##  Max.   :112.885   Max.   :64.621   Max.   :2349.8   Max.   :21.40  
##    rtransfer        rgrowth         rsenesced         diseased      
##  Min.   : 0.00   Min.   : 9.688   Min.   : 1.000   Min.   :  0.000  
##  1st Qu.: 0.00   1st Qu.:29.032   1st Qu.: 9.475   1st Qu.:  1.402  
##  Median : 0.00   Median :34.324   Median :25.254   Median : 14.454  
##  Mean   : 1.18   Mean   :42.412   Mean   :19.727   Mean   : 46.464  
##  3rd Qu.: 0.00   3rd Qu.:57.347   3rd Qu.:27.492   3rd Qu.: 84.794  
##  Max.   :21.40   Max.   :79.655   Max.   :37.738   Max.   :142.793  
##     severity           lat             lon       
##  Min.   :0.0000   Min.   :14.68   Min.   :121.3  
##  1st Qu.:0.1904   1st Qu.:14.68   1st Qu.:121.3  
##  Median :0.5299   Median :14.68   Median :121.3  
##  Mean   :1.3461   Mean   :14.68   Mean   :121.3  
##  3rd Qu.:2.6433   3rd Qu.:14.68   3rd Qu.:121.3  
##  Max.   :4.4218   Max.   :14.68   Max.   :121.3</code></pre>
<div id="dry-season-severity" class="section level3">
<h3 class="hasAnchor">
<a href="#dry-season-severity" class="anchor"></a>Dry season severity</h3>
<p>Check the disease progress curve for the dry season.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">bb_dry</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dates</span>,
           y <span class="op">=</span> <span class="va">severity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Severity (%)"</span>,
       x <span class="op">=</span> <span class="st">"Date"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Bacterial blight disease progress over time"</span>,
       subtitle <span class="op">=</span> <span class="st">"Results for dry season year 2000 at IRRI Zeigler Experiment
       Station shown"</span>,
       caption <span class="op">=</span> <span class="st">"Weather data acknowledgement: These data were obtained from
       the NASA Langley Research Center POWER Project funded through the NASA
       Earth Science Directorate Applied Science Program."</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_light</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="epirice_files/figure-html/dry_plot_severity-1.png" width="672"></p>
<p>Calculate the AUDPC using the <code><a href="https://rdrr.io/pkg/epifitter/man/AUDPC.html">AUDPC()</a></code> from <em>epifitter</em> for both seasons and compare.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Dry season</span>
<span class="fu"><a href="https://rdrr.io/pkg/epifitter/man/AUDPC.html">AUDPC</a></span><span class="op">(</span>
  time <span class="op">=</span> <span class="va">bb_dry</span><span class="op">$</span><span class="va">simday</span>,
  y <span class="op">=</span> <span class="va">bb_dry</span><span class="op">$</span><span class="va">severity</span>,
  y_proportion <span class="op">=</span> <span class="cn">FALSE</span>,
  type <span class="op">=</span> <span class="st">"relative"</span>
<span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.01345592</code></pre>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Wet season</span>
<span class="fu"><a href="https://rdrr.io/pkg/epifitter/man/AUDPC.html">AUDPC</a></span><span class="op">(</span>
  time <span class="op">=</span> <span class="va">bb_wet</span><span class="op">$</span><span class="va">simday</span>,
  y <span class="op">=</span> <span class="va">bb_wet</span><span class="op">$</span><span class="va">severity</span>,
  y_proportion <span class="op">=</span> <span class="cn">FALSE</span>,
  type <span class="op">=</span> <span class="st">"relative"</span>
<span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1017425</code></pre>
<p>The AUDPC of the wet season is greater than that of the dry season. Checking the data and referring to the curves, the wet season severity reaches a peak value of 40.17% and the dry season tops out at 4.42%. So this meets the expectations that the wet season AUDPC is higher than the dry season, which was predicted to have less disease severity.</p>
</div>
</div>
<div id="references" class="section level1">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<p>Kaique dos S. Alves and Emerson M. Del Ponte (2020). epifitter: Analysis and Simulation of Plant Disease Progress Curves. R package version 0.2.0. URL: <a href="https://CRAN.R-project.org/package=epifitter" class="uri">https://CRAN.R-project.org/package=epifitter</a>.</p>
<p>Serge Savary, Andrew Nelson, Laetitia Willocquet, Ireneo Pangga and Jorrel Aunario. Modeling and mapping potential epidemics of rice diseases globally. <em>Crop Protection</em>, Volume 34, 2012, Pages 6-17, ISSN 0261-2194 DOI: <a href="https://doi.org/10.1016/j.cropro.2011.11.009">10.1016/j.cropro.2011.11.009</a>.</p>
<p>Gregory Shaner and R. E. Finney. "The effect of nitrogen fertilization on the expression of slow-mildewing resistance in Knox wheat. <em>Phytopathology</em> Volume 67.8, 1977, Pages 1051-1056.</p>
<p>Adam Sparks (2018). nasapower: A NASA POWER Global Meteorology, Surface Solar Energy and Climatology Data Client for R. Journal of Open Source Software, 3(30), 1035, DOI: <a href="https://doi.org/10.21105/joss.01035">10.21105/joss.01035</a>.</p>
<p>Adam Sparks (2020). <em>nasapower: NASA-POWER Data from R</em>. R package version 3.0.1, URL: <a href="https://CRAN.R-project.org/package=nasapower" class="uri">https://CRAN.R-project.org/package=nasapower</a>.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Adam Sparks, Robert Hijmans, Serge Savary, Ireno Pangga, Jorrel Aunario.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
